### ISSUE TITLE
Using KeOps when calling prepare_, apply_, finalize_

### ISSUE THREAD

**Issue by fwilliams** [FalkonML/falkon#15]
I've extended the `DotProductKernel` with my own custom kernel and have run into some issues with memory.

It seems that when evaluating the function found after doing Kernel Ridge Regression, KeOps gets used. 

However, in the fitting phase, `prepare_`, `apply_` and `finalize_` get called which don't use KeOps. Because of this, I run out of memory when trying to fit very large inputs.

Is there a way to use KeOps for the fitting phase? Is there a reason this isn't being done by default?

Thanks in advance!

**Comment by fwilliams** [comment]
It seems that `prepare_`, `apply_` and `finalize_` get called only once at the beginning of the fitting phase. I still don't fully understand why though.

**Comment by Giodiro** [comment]
Hi @fwilliams ,
To support fast kernel-vector products with both low and high dimensions you will need to write your own `_keops_mmv_impl` function which is the KeOps formula, and `prepare_`, `apply_`, `finalize_`. 

When you are in the low-dimensional case (when KeOps should work well), the `prepare_`, ... functions will only be called once when Falkon needs to compute the full kernel (at the start of the `fit` call).

In general, what I've done up to now has been to ensure that `prepare_`, `apply_`, `fit_` **do not allocate any memory** (for example in the `apply_` I do `out.addmm_(X1, X2)` for the product `X1@X2`, and in `finalize_` I always use the in-place pytorch operators (i.e. those that end in an underscore).
The caller is responsible for allocations so that it can decide how to split the data matrices without running out of memory.

Let me know something more about your kernel, if possible share your implementation so I can have a look at what might be causing memory issues!

**Comment by fwilliams** [comment]
Hi @Giodiro , thanks a lot for the reply!

I implemented my own `_keops_mmv_impl` and during the fitting process at the beginning, it is properly using KeOps.

The memory issue comes when I use a very large number of nystrom samples (let's say `N`). It seems that even the dot product kernel does allocate a full `N x N` matrix (`out` in the case of `DotProductKernel`). Why is this initial allocation necessary? Can it be replaced with KeOps?

Let me clean up my code a bit and I'll post an example later.

**Comment by Giodiro** [comment]
Hi! If the number of Nystrom samples (that is the `M` parameter) is high you may run out of RAM (while you should not run out of GPU RAM, at least in theory :))

There is no way around storing the `M x M` matrix unfortunately.. in practice, unless your dataset is super hard you can usually set it quite low. But It's true that to set something like `M=100k` you will need a lot of RAM, probably not less than 64GB!

**Comment by fwilliams** [comment]
Is the initial NxN matrix materialized in RAM? It seems like it gets materialized in GPU ram? If it were in RAM and the keops iterates were on the GPU this would be fine.

**Comment by Giodiro** [comment]
It's only fully materialized in CPU memory. Only smaller blocks of it are built on the GPU: you can have a look at [the `_generic_fmm` function](https://github.com/FalkonML/falkon/blob/96118df9f5006150d506b8530bd3a9ffaeee072a/falkon/mmv_ops/fmm_cuda.py#L92). 

The GPU memory allocations occur between lines 128-134. The data matrices are split into chunks (have a look at the calls to `narrow`), and then `_prepare`, `_apply`, `_finalize` are called on the chunks only. The result is moved back to the CPU on lines 171-174.

Could you share the error you're getting?

**Comment by fwilliams** [comment]
It seems like a CUDA out of memory error. Here is the message:

```
MainProcess.MainThread::[Calcuating Preconditioner of size 100000]
Preconditioner will run on 1 GPUs
--MainProcess.MainThread::[Kernel]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=2 : out of memory
--MainProcess.MainThread::[Kernel] complete in 0.000s
MainProcess.MainThread::[Calcuating Preconditioner of size 100000] complete in 0.000s
Traceback (most recent call last):
  File "test_falkon_fit.py", line 107, in <module>
    main()
  File "test_falkon_fit.py", line 101, in main
    mdl = fit_model(xb, yb, args.penalty, num_ny, mode="falkon", maxiters=args.max_iters)
  File "test_falkon_fit.py", line 36, in fit_model
    model.fit(x, y)
  File "/home/francis/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/models/falkon.py", line 185, in fit
    precond.init(ny_points)
  File "/home/francis/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/preconditioner/flk_preconditioner.py", line 88, in init
    C = create_same_stride((M, M), X, dtype=dtype, device=dev,
  File "/home/francis/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py", line 41, in create_same_stride
    return create_C(size, dtype, device, pin_memory)
  File "/home/francis/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py", line 121, in create_C
    return _new_strided_tensor(tuple(size), stride, dtype, device, pin_memory)
  File "/home/francis/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py", line 26, in _new_strided_tensor
    return torch.empty_strided(
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/THC/THCCachingHostAllocator.cpp:278
```

**Comment by Giodiro** [comment]
Ha! It's a bug in the code since it doesn't tell you explicitly, but what I think is going on is that you're passing the data to `fit` as CUDA tensors, and the code thinks you want to do everything in the GPU (and then goes on to fail miserably).

I'll add some checks for this tomorrow, but in the meantime could you try to pass CPU tensors to fit and see whether it works?
Thanks :)

**Comment by fwilliams** [comment]
I was calling fit with CPU tensors to begin with. Here's some debug output:
```python
model = falkon.Falkon(kernel=kernel, penalty=penalty, M=num_ny, options=opts, maxiter=maxiters)
print("fit(x, y) getting tensors x.device =", x.device, "and y.device =", y.device, "x.shape =", x.shape, "and y.shape =", y.shape)
model.fit(x, y)
```

which outputs:
```
fit(x, y) getting tensors x.device = cpu and y.device = cpu x.shape = torch.Size([300000, 4]) and y.shape = torch.Size([300000])
```

**Comment by Giodiro** [comment]
Ok, that's unexpected. There must be some place in the falkon code which converts your CPU tensors to CUDA. 
Does the error occur if you run something like this?

```python
import falkon
import torch
kernel = falkon.kernels.GaussianKernel(3)
opts = falkon.FalkonOptions(debug=True)
x = torch.randn(300000, 4)
y = torch.randn(300000)
model = falkon.Falkon(kernel=kernel, penalty=1e-4, M=50000, options=opts, maxiter=5)
model.fit(x, y)
```

**Comment by fwilliams** [comment]
Yes the same error occurs. Here's the backtrace:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-5f2018e1f24d> in <module>
      6 y = torch.randn(300000)
      7 model = falkon.Falkon(kernel=kernel, penalty=1e-4, M=50000, options=opts, maxiter=5)
----> 8 model.fit(x, y)

~/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/models/falkon.py in fit(self, X, Y, Xts, Yts)
    183                       ("CPU" if pc_opt.use_cpu else ("%d GPUs" % self.num_gpus)))
    184             precond = falkon.preconditioner.FalkonPreconditioner(self.penalty, self.kernel, pc_opt)
--> 185             precond.init(ny_points)
    186             self.precond = precond
    187 

~/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/preconditioner/flk_preconditioner.py in init(self, X)
     86         with TicToc("Kernel", debug=self.params.debug):
     87             if isinstance(X, torch.Tensor):
---> 88                 C = create_same_stride((M, M), X, dtype=dtype, device=dev,
     89                                        pin_memory=self._use_cuda)
     90             else:  # If sparse tensor we need fortran for kernel calculation

~/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py in create_same_stride(size, other, dtype, device, pin_memory)
     39         return create_fortran(size, dtype, device, pin_memory)
     40     else:
---> 41         return create_C(size, dtype, device, pin_memory)
     42 
     43 

~/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py in create_C(size, dtype, device, pin_memory)
    119         raise ValueError("create_C can only create 1 or 2D tensors.")
    120 
--> 121     return _new_strided_tensor(tuple(size), stride, dtype, device, pin_memory)
    122 
    123 

~/miniconda3/envs/kernel-metalearning/lib/python3.8/site-packages/falkon/utils/tensor_helpers.py in _new_strided_tensor(size, stride, dtype, device, pin_memory)
     24 
     25     # noinspection PyArgumentList
---> 26     return torch.empty_strided(
     27         size=size, stride=stride,
     28         dtype=dtype, device=device,

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/THC/THCCachingHostAllocator.cpp:278


```

**Comment by Giodiro** [comment]
On second thought, I think you're running out of CPU memory, although the error message from pytorch doesn't help:

the fact that the error is in the `THCCachingHostAllocator` (keyword Host) means that it's CPU RAM. The fact that it's a CUDA runtime error is because the code tries to allocate 'pinned' memory which is handled by the CUDA driver and basically means that transfers from CPU(pinned memory) to GPU will be faster.

Now pinned memory should not be inherently smaller than your available RAM, although if you are at the very at the limit of RAM usage it may be?? If you want to have a go, you can try setting `pin_memory=False` [here](https://github.com/FalkonML/falkon/blob/96118df9f5006150d506b8530bd3a9ffaeee072a/falkon/preconditioner/flk_preconditioner.py#L89) but I don't guarantee that it will work.. In fact, you will probably see a normal out of memory error, or lots of disk swapping.

In case you would like a hand in choosing an appropriate value for `M`: how much RAM do you have available? And what's the data-type of your data (e.g. float32 or float64)?

Sorry, I should have caught it before. This error message is super confusing

**Comment by fwilliams** [comment]
Thanks for the update. Yes, this was an issue with running out of memory due to pinning! Thanks a lot for all of your help!
